version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm ci --quiet
  build:
    commands:
      - VITE_APP_GIT_SHA=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - npm run build
  post_build:
    commands:
      - aws --output text s3 sync --delete --sse AES256 --acl private --only-show-errors --cache-control max-age=2592000 dist/ s3://$S3_BUCKET
      - aws --output text s3 cp --sse AES256 --acl private --only-show-errors --cache-control max-age=300 dist/index.html s3://$S3_BUCKET/index.html
      - aws --output text cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths /\*
